<a href="https://colab.research.google.com/github/j-claudinei-f/j-claudinei-f/blob/main/Regress%C3%A3o_J%C3%BAlia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Sobre a regressão de Júlia**

José Claudinei Ferreira

Universidade Federal de Alfenas

**Introdução**

Tem circulado na internet alguns vídeos sobre um método de calcular raiz quadrada (natural e) de um número natural $a$, por meio da fórmula $$\sqrt{a}=\frac{d-k^2}{2k},$$ em que precisamos determinar $d$ e $k$.

Esse método foi nomeado de [regressão de Júlia](https://youtu.be/3UC2J_QrqMI?si=Nx9bCSyzJ_uGF6P-), porque parece que ideia começou da observação, feita pelo professor Frederico, de como a sua aluna Júlia lidou com um problema de cálculo de raiz quadrada.

Como mencionado nos vídeos é uma forma de lidar com vários conceitos de aritmética e também de gerar motivação para que professores e alunos criem e divulguem conhecimento.

Mas cabe observar que a parte do ineditismo (da fórmula), eu discordo!

E sobre a relação da fórmula e da utilidade dela nos vídeos escrevo algumas observações.

**Da minha interpretação dos vídeos**

Existe um artigo sobre o tema na [RPM 2023](https://www.rpm.org.br/) ([link](https://youtube.com/shorts/ipUsQdcaxcY?si=2uxL4MynS8z07vTg) do texto em vídeo), que descreve que o processo vem do produto notável $(x+k)^2=x^2+2kx+k^2$, para $a$ e $k$ números reais (números naturais no vídeo).

Se $x^2=a$ e $k$ é um número real, então $(x+k)^2=x^2+2kx+k^2=a+d$, para $d=(x+k)^2-a$, ou $$x=\frac{((x+k)^2-a)-k^2}{2k},\qquad k\neq 0,$$ para $x,\,k$ números reais.

Mas, da observação de [alguns vídeos](https://youtube.com/shorts/VrKue9y49IU?si=JEPtF2238yCdIhpi), entendi outra coisa; entendi o seguinte:

Dado um número real e positivo $a$, para calcular a raiz quadrada desse número, você pode seguir os itens:



**1.** Primeiro defina $$f(x)=x^2-a,$$ que pode ser visto como uma forma de ver o quão longe está $x^2$ de $a$, ou o quão longe está $x$ de $\sqrt{a}$.



**2.**  Escolha um valor inicial $x_0$, como aproximação da suposta raiz quadrada de $a$, ou seja, $x_0\approx \sqrt{a}$.

Calcule $f(x_0)=x_0^2-a$.

Por exemplo, em [um vídeo](https://youtu.be/CT1NznBYFVQ?si=ZJUQSbwg9pWUSNi3) é escolhido $a=69139225$ e $x_0=8355$, depois de estimativas, usando argumentos de aritmética) para mais e para menos da raiz quadrada de $a$ (que vejo como um [processo de aproximações sucessivas](https://llsaboya.com/pt-br/blog/notas/modelo-de-aproximacao-sucessiva-sam/).

In [ ]:
a,x0=69139225,8355  # Comandos para usar calculadora em linguagem Python.

a,x0

(69139225, 8355)

Definido $f(x)$

In [ ]:
def f(x):
  return x**2-a

Obtemos

In [ ]:
f(x0)

666800

**3.**  Agora defina $$g(x)=\frac{f(x)}{2x},\qquad x>0.$$

In [ ]:
def g(x):
 return f(x)/(2*x)

Obtemos

In [ ]:
g(x0)

39.904248952722924

que é aproximadamente 40.

No vídeo, me parece que a ideia é tomar $d\approx f(x_0)$ e $k\approx g(x_0)$.

Uma aproximação para a raiz quadrada seria $$\frac{f(x_0)-g(x_0)^2}{2g(x_0)}=h(x_0)=\frac{a+3x_0^2}{4x_0}.$$

<font color=blue> O que me diz que há cálculos desnecessários no vídeo, antes das observações sobre arredondamento.

**4.**  Mas isso me leva a definir $$h(x)=\frac{f(x)-g(x)^2}{2g(x)}=\frac{(x^2-a)-\left(\frac{x^2-a}{2x}\right)^2}{2\frac{x^2-a}{2x}}=\frac{a+3x^2}{4x},\qquad x>0.$$



In [ ]:
def h(x):
  return (a+3*x**2)/(4*x)

E obtemos

In [ ]:
x1=h(x0)

h(x1)

8325.035992800944

<font color=blue> Aqui tem o pulo do gato, já que o Frederico sabe que $\sqrt{a}$, do $a$ dele, é um número natural.

Note que se arredondar $g(x_0)\approx 40=k$ e tomar $d=f(x_0)$, você vai obter

In [ ]:
(666800-40**2)/(2*40)

8315.0

No vídeo ele faz outro arredondamento (bem forçado, a meu ver) $$\frac{f(x_0)}{2x_0}=\frac{666800}{2\times 8355}\approx \frac{667000}{2\times 8000}$$

In [ ]:
(667000/8000)/2

41.6875

Que ele arredonda para $40$.

É isso que ele usa para fazer a coisa $$\frac{f(x_0)-g(x_0)^2}{2g(x_0)}\approx 8315$$ <font color=red>"funcionar magicamente".

**5. De modo geral eu entendi o seguinte:**

Escolha um valor positivo $x_0$; o que quiser.

Tome a relação de recorrência (ou sequência recursiva, como na BNCC) $$x_{n+1}=h(x_n)$$ e note que, se $x_n$ convergir para algum $p$, então $$p=h(p)=\frac{a+3p^2}{4p}\Longrightarrow 4p^2=3p^2+a\Longrightarrow p^2=a\Longrightarrow p=\pm\sqrt{a}.$$

Você pode checar que $h(\sqrt{a})=\sqrt{a}$, ou seja, $\sqrt{a}$ é [ponto fixo](https://pt.wikipedia.org/wiki/Ponto_fixo#:~:text=Teorema%20do%20ponto%20fixo%20de%20Kakutani%3A%20um%20teorema,de%20um%20espa%C3%A7o%20euclidiano%20tenha%20um%20ponto%20fixo.) de $h(x)$.

<font color=blue> O que o Frederico faz é escolher $x_0$ próximo de $\sqrt{a}$ e ir ajustando $x_n$ para o inteiro mais próximo, ajustando $g(x_{n-1})$ na verdade, em cada iteração. Isso acelera a convergência; com algum (acho que muito) treino, encontra a raiz logo no primeiro passo.

Sem esse arredondamento, para $n=20$ e escolhendo $a=69139225$ e $x_0=8355$, como antes, temos:

In [ ]:
n=20

xn=x0
for i in range(0,n):
  xn=h(xn)

xn

8315.000038330483

Note que

In [ ]:
f(xn)

0.6374359428882599

O que sugere que $\sqrt{a}=8315$.

In [ ]:
f(8315)

0

Note que poderia escolher $x_0=1$, ou seja, se não for bom no chute inicial, ou não quiser brincar com aritmética. Mas vai precisar de $n$ maior:

In [ ]:
n=50

x=1                   # x0 escolhido
for i in range(0,n):
  x=h(x)

x

8315.000756763982

**E porque funciona?**

Dados dois números reais $x$ e $y$, ambos suficientemente próximos de $\sqrt{a}$, então
$$|h(x)-h(y)|=\left|\frac{a+3x^2}{4x}-\frac{a+3y^2}{4y}\right|=|x-y|\left|\frac{3}{4}-\frac{a}{4xy}\right|\approx |x-y|\frac{2}{4}.$$

E segue que, se $x_0^2\approx a$, então $x_n$ converge para $\sqrt{a}$, porque
$$x_{n+1}-\sqrt{a}=h(x_{n})-h(\sqrt{a})\approx \frac{1}{2}(x_{n}-\sqrt{a}).$$

Isso nos diz que
$$|x_{n+1}-\sqrt{a}|<\frac{3}{4}|x_{n}-\sqrt{a}|<\left(\frac{3}{4}\right)^n|x_{1}-\sqrt{a}|\to 0,$$ bem rápido. <font color=green> E ainda corrige arredondamentos pequenos.



De outra forma, como $$h'(x)=\frac{(3x^2+a)'4x-(4x)'(3x^2+a)}{(4x)^2}=\frac{6x\times 4x-4\times (3x^2+a)}{16x^2}=\frac{3}{4}-\frac{a}{4x^2}.$$

Se $x^2\approx a$, então $$0<h'(x)\approx \frac{2}{4}<3/4<1.$$  

E segue que, se $x_0^2\approx a$, então $x_n$ converge para $\sqrt{a}$, porque
$$x_{n+1}-\sqrt{a}=h(x_{n})-h(\sqrt{a})=h'(s_n)(x_{n}-\sqrt{a}),$$ para algum $s_n$ entre $x_{n+1}$ e $\sqrt{a}$ (Veja o [teorema do valor médio](https://pt.wikipedia.org/wiki/Teorema_do_valor_m%C3%A9dio)).


**E ainda poderia ter menos cálculos**

Se em vez de escolher $$h(x)=\frac{3x^2+a}{4x}=x-\frac{x^2-a}{4x}=x-\frac{g(x)}{2}=x-\frac{f(x)}{2f'(x)},$$ o Frederico tivesse escolhido $$q(x)=\frac{x^2+a}{2x}=x-\frac{x^2-a}{2x}=x-g(x)=x-\frac{f(x)}{f'(x)},\qquad x>0,$$ ele teria o método de Newtom, por exemplo, que é bem mais rápido.

Sobre isso [eu já escrevi algumas coisas](https://rmu.sbm.org.br/wp-content/uploads/sites/11/sites/11/2021/11/3-Quandos-os-metodos-de-Eules-e-Newton-coinciden.pdf) ....

Por exemplo, escolhendo $a=69139225$ e $x_0=8355$, como antes:

In [ ]:
def q(x):
  return (x**2+a)/(2*x)

Temos

In [ ]:
q(x0)

8315.095751047276

<font color=green> Que já é uma aproximação muito boa, sem nenhuma mágica!

Mas, escolhendo $a=69139225$ e $x_0=1$ e $n=20$ vai ter uma ótima aproximação:

In [ ]:
n=20

x=1                   # x0 escolhido
for i in range(0,n):
  x=q(x)

x

8315.0

**Para terminar**

Sugiro que clike no link "Open in Colab" no topo da página, e troque os valores de $a$, $x_0$ e $n$ e brinque com os blocos de comando em Python (aperte Ctrl+Enter ou clique no play de cada bloco).

E repito: Como mencionado nos vídeos é uma forma de lidar com vários conceitos de aritmética e também de gerar motivação para que professores e alunos criem e divulguem conhecimento.

<font color=blue> E acrescento: Pode ser uma forma da trabalhar com relações de recorrência (ou sequência recursiva, como na BNCC).

Gostei de pensar nisso: obrigado Douglas por me enviar o vídeo, e obrigado Frederico e Júlia.

Termino minhas observações, por agora!

**Mais uma divagação**

Seja $$r(x)=\frac{px^2+a}{(p+1)x},\qquad x>0,$$ para algum $p>0$.

Assim, $$r'(x)=\frac{p}{p+1}-\frac{a}{(p+1)x^2}\approx \frac{p-1}{p+1}<\frac{p}{p+1}< 1,\qquad x^2\approx a,\qquad p\geq 1.$$

Portanto, a relação de recorrência $$x_{n+1}=r(x_n),$$ para alguma escolha de $x_0$, com $x_0\approx a$, converge para $\sqrt{a}=r(\sqrt{a})$.

Como $|r'(x)|$ é menor, quando $x^2\approx a$. Então, se $p=1$, temos  $r'(x)\approx 0$, o que sugere que o método de Newton é a melhor escolha para resolver a equação $x^2-a=0$, por meio das relações de recorrência descritas neste texto.